import { useRef, useState } from 'react'
import { CheckCircle2, Download, FileSpreadsheet, FileText, LoaderCircle, RotateCcw, UploadCloud, XCircle } from 'lucide-react'
import { api } from '../api'
import type { Strategy } from '../types'

export default function Batch(){
 const input=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null);const [strategy,setStrategy]=useState<Strategy>('mask');const [running,setRunning]=useState(false);const [job,setJob]=useState<any>(null);const [error,setError]=useState('')
 async function run(){if(!file)return;setRunning(true);setError('');try{setJob(await api.batch(file,strategy))}catch(e){setError(e instanceof Error?e.message:'批处理失败')}finally{setRunning(false)}}
 function download(){if(!job)return;const csv='row,entity_count,redacted_text\n'+job.results.map((r:any)=>`${r.row},${r.entity_count},"${r.redacted_text.replaceAll('"','""')}"`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='privshield-batch-result.csv';a.click()}
 function choose(next:File|null){setError('');if(!next)return;if(next.size>5*1024*1024){setFile(null);setError('文件超过 5 MB，请拆分后重新上传');return}setFile(next)}
 return <div className="page"><header className="page-header"><div><div className="eyebrow">BATCH PROCESSING</div><h1>批量隐私处理</h1><p>对 TXT、CSV 与 JSON 数据进行一致策略脱敏，高风险记录可转入人工复核。</p></div>{job&&<button className="btn ghost" onClick={()=>{setJob(null);setFile(null)}}><RotateCcw size={16}/>新建任务</button>}</header>
 {!job?<div className="batch-grid"><section className="panel upload-panel"><div className="section-heading"><div><span>STEP 01</span><h2>上传数据文件</h2></div></div><button className={`drop-zone ${file?'has-file':''}`} onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0]||null)}}><input ref={input} type="file" accept=".txt,.csv,.json" hidden onChange={e=>choose(e.target.files?.[0]||null)}/>{file?<><FileSpreadsheet size={38}/><strong>{file.name}</strong><span>{(file.size/1024).toFixed(1)} KB · 点击更换文件</span></>:<><UploadCloud size={38}/><strong>将文件拖到这里，或点击选择</strong><span>支持 UTF-8 编码的 TXT / CSV / JSON，最大 5 MB</span></>}</button><div className="format-hints"><div><FileText/><span><strong>TXT</strong><small>每行一条文本</small></span></div><div><FileSpreadsheet/><span><strong>CSV</strong><small>自动识别 text 列</small></span></div><div><span className="json-icon">{ }</span><span><strong>JSON</strong><small>结构化记录</small></span></div></div></section>
 <section className="panel batch-config"><div className="section-heading"><div><span>STEP 02</span><h2>处理配置</h2></div></div><label title="字段由后端按文件格式自动识别"><span>文本字段（自动识别）</span><select disabled><option>自动识别</option></select></label><label><span>脱敏策略</span><select value={strategy} onChange={e=>setStrategy(e.target.value as Strategy)}><option value="mask">一致性掩码</option><option value="pseudonymize">确定性伪名</option><option value="generalize">层级泛化</option></select></label><div className="config-checks" title="这些能力由当前服务端策略统一启用"><label><input type="checkbox" checked disabled readOnly/>疑难句按服务端策略补漏</label><label><input type="checkbox" checked disabled readOnly/>高风险记录转人工复核</label><label><input type="checkbox" checked disabled readOnly/>生成完整审计报告</label></div><button className="btn primary full" disabled={!file||running} onClick={run}>{running?<LoaderCircle className="spin"/>:<UploadCloud/>}创建批处理任务</button>{error&&<div className="inline-error"><XCircle/>{error}</div>}</section></div>:
 <><section className="panel job-summary"><div className="job-success"><CheckCircle2/><div><small>任务 {job.job_id}</small><h2>批处理已完成</h2><p>{job.total} 条记录已完成识别、脱敏和偏移校验。</p></div></div><div className="job-kpis"><div><span>处理进度</span><strong>100%</strong><i><b style={{width:'100%'}}/></i></div><div><span>成功记录</span><strong>{job.total}</strong></div><div><span>失败记录</span><strong>0</strong></div><div><span>待人工复核</span><strong>{job.results.filter((x:any)=>x.entity_count>3).length}</strong></div></div></section>
 <section className="panel results-table"><div className="table-head"><div><h2>结果预览</h2><span>仅展示前 20 条记录</span></div><button className="btn primary" onClick={download}><Download size={16}/>下载脱敏结果</button></div><div className="table-wrap"><table><thead><tr><th>行号</th><th>原始文本</th><th>脱敏结果</th><th>实体数</th><th>状态</th></tr></thead><tbody>{job.results.slice(0,20).map((r:any)=><tr key={r.row}><td>#{r.row}</td><td>{r.text}</td><td>{r.redacted_text}</td><td><b>{r.entity_count}</b></td><td><span className="success-chip"><CheckCircle2/>完成</span></td></tr>)}</tbody></table></div></section></>}
 </div>
}
