import { useEffect, useState } from 'react'
import { Check, ChevronRight, Clock3, FileText, Fingerprint, Save, Settings2, SlidersHorizontal } from 'lucide-react'
import { api } from '../api'
import type { Strategy } from '../types'
const types=[['PERSON','姓名'],['ORG','机构'],['LOCATION','地点'],['ADDRESS','详细地址'],['PHONE','电话号码'],['EMAIL','电子邮箱'],['ID_CARD','身份证件'],['BANK_CARD','银行卡号']]
export default function History(){const [tab,setTab]=useState<'history'|'policy'|'audit'>('history');const [data,setData]=useState<any>({items:[],audits:[]});const [policies,setPolicies]=useState<Record<string,Strategy>>({});const [saved,setSaved]=useState(false);useEffect(()=>{api.history().then(setData);api.policies().then(x=>setPolicies(x.policies))},[]);async function save(){await api.savePolicies(policies);setSaved(true);setTimeout(()=>setSaved(false),2000)}return <div className="page"><header className="page-header"><div><div className="eyebrow">TRACEABILITY & POLICY</div><h1>历史与策略中心</h1><p>回溯每一次处理任务，管理实体脱敏策略与人工操作记录。</p></div></header><div className="page-tabs"><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><Clock3/>处理历史</button><button className={tab==='policy'?'active':''} onClick={()=>setTab('policy')}><SlidersHorizontal/>策略配置</button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}><Fingerprint/>审计日志</button></div>
 {tab==='history'&&<section className="panel history-panel"><div className="table-head"><div><h2>最近处理任务</h2><span>保留输入摘要、模型版本、实体数量与风险等级</span></div></div>{data.items.length?<div className="history-list">{data.items.map((item:any)=><div className="history-item" key={item.id}><div className="file-icon"><FileText/></div><div className="history-main"><strong>{item.preview||'未命名文本任务'}</strong><span>{item.id} · {new Date(item.created_at).toLocaleString()}</span></div><span className={`risk-level ${item.risk}`}>{item.risk==='high'?'高风险':item.risk==='medium'?'中风险':'低风险'}</span><b>{item.entity_count} 个实体</b><button><ChevronRight/></button></div>)}</div>:<div className="queue-empty large"><Clock3/><strong>暂无历史任务</strong><p>在工作台完成一次检测后，记录会自动出现在这里。</p></div>}</section>}
 {tab==='policy'&&<div className="policy-layout"><section className="panel policy-panel"><div className="section-heading"><div><span>ENTITY POLICIES</span><h2>按实体类型配置默认策略</h2></div><button className="btn primary" onClick={save}>{saved?<Check/>:<Save/>}{saved?'已保存':'保存策略'}</button></div><div className="policy-table"><div className="policy-row policy-head"><span>实体类型</span><span>默认处理策略</span><span>保护级别</span></div>{types.map(([key,label])=><div className="policy-row" key={key}><span><i className={`legend-dot entity-${key}`}/><b>{label}</b><small>{key}</small></span><select value={policies[key]||'mask'} onChange={e=>setPolicies({...policies,[key]:e.target.value as Strategy})}><option value="mask">一致性掩码</option><option value="pseudonymize">确定性伪名</option><option value="generalize">层级泛化</option></select><span className={['ID_CARD','BANK_CARD','PHONE'].includes(key)?'level critical':'level standard'}>{['ID_CARD','BANK_CARD','PHONE'].includes(key)?'严格':'标准'}</span></div>)}</div></section><aside className="panel model-settings"><div className="section-heading"><div><span>MODEL ROUTING</span><h2>模型与路由</h2></div></div><label><span>主核验模型</span><select><option>Qwen3-14B</option><option>Qwen3-14B-AWQ</option><option>Qwen3-8B</option></select></label><label><span>NER 适配器</span><select><option>XLM-RoBERTa NER</option><option>CLUENER 中文模型</option></select></label><div className="route-setting"><div><span>候选复核阈值</span><b>0.78</b></div><input type="range" min="50" max="95" defaultValue="78"/></div><div className="route-setting"><div><span>最大 LLM 路由比例</span><b>30%</b></div><input type="range" min="5" max="100" defaultValue="30"/></div><div className="model-security"><Settings2/><p><strong>隐私安全模式</strong><span>模型服务与应用在同一受控服务器运行，不向第三方发送原文。</span></p></div></aside></div>}
 {tab==='audit'&&<section className="panel history-panel"><div className="table-head"><div><h2>不可变操作记录</h2><span>记录人工接受、拒绝、改类与策略变更</span></div></div>{data.audits.length?<div className="audit-list">{data.audits.map((x:any)=><div className="audit-row" key={x.id}><Fingerprint/><span><strong>{x.operation}</strong><small>{x.task_id} · span {x.payload?.span_id}</small></span><time>{new Date(x.created_at).toLocaleString()}</time><code>{x.payload?.before||'—'} → {x.payload?.after||'—'}</code></div>)}</div>:<div className="queue-empty large"><Fingerprint/><strong>暂无人工操作</strong><p>复核操作将按时间顺序记录在此处。</p></div>}</section>}
 </div>}
