import { useEffect, useState } from 'react'
import { Check, ChevronRight, Clock3, Download, FileText, Fingerprint, Save, Settings2, ShieldAlert, SlidersHorizontal, Trash2 } from 'lucide-react'
import { api } from '../api'
import { allEntityTypes, type DetectResult, type EntityType, type Strategy } from '../types'

const labels: Record<EntityType,string> = { PERSON:'姓名',ORG:'机构',LOCATION:'地点',ADDRESS:'详细地址',PHONE:'电话',EMAIL:'邮箱',ID_CARD:'身份证',BANK_CARD:'银行卡',PASSPORT:'护照',CUSTOM:'自定义' }
function saveJson(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

export default function History(){
  const [tab,setTab]=useState<'history'|'policy'|'audit'>('history')
  const [data,setData]=useState<any>({items:[],audits:[]})
  const [policies,setPolicies]=useState<Record<string,Strategy>>({})
  const [selected,setSelected]=useState<DetectResult|null>(null)
  const [retention,setRetention]=useState(30)
  const [message,setMessage]=useState('')
  const [saved,setSaved]=useState(false)
  async function refresh(){setData(await api.history())}
  useEffect(()=>{refresh();api.policies().then(x=>setPolicies(x.policies))},[])
  async function save(){await api.savePolicies(policies);setSaved(true);setTimeout(()=>setSaved(false),2000)}
  async function openTask(id:string){try{setSelected(await api.getTask(id))}catch(error){setMessage(error instanceof Error?error.message:'读取失败')}}
  async function removeTask(id:string){if(!window.confirm('确认删除该任务原文、结果和审计记录？'))return;await api.deleteTask(id);if(selected?.task_id===id)setSelected(null);await refresh();setMessage('任务已彻底删除。')}
  async function purge(){if(!window.confirm(`确认清除 ${retention} 天以前的全部任务与审计记录？`))return;const result=await api.purgeTasks(retention);await refresh();setMessage(`已清除 ${result.deleted} 个过期任务。`)}
  return <div className="page"><header className="page-header"><div><div className="eyebrow">TRACEABILITY & RETENTION</div><h1>历史、审计与数据保留</h1><p>回溯每次处理，管理实体默认策略，并按保留期限清除含原文的任务数据。</p></div></header>{message&&<div className="notice-banner">{message}</div>}<div className="page-tabs"><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><Clock3/>处理历史</button><button className={tab==='policy'?'active':''} onClick={()=>setTab('policy')}><SlidersHorizontal/>默认策略</button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}><Fingerprint/>审计日志</button></div>
  {tab==='history'&&<div className="history-layout"><section className="panel history-panel"><div className="table-head"><div><h2>最近处理任务</h2><span>任务原文仅用于偏移复核，可随时单条删除或按期限批量清除。</span></div><div className="retention-actions"><label>清除<input type="number" min="1" max="3650" value={retention} onChange={event=>setRetention(Number(event.target.value))}/>天前</label><button className="btn ghost danger" onClick={purge}><Trash2/>执行清除</button></div></div>{data.items.length?<div className="history-list">{data.items.map((item:any)=><div className="history-item" key={item.id}><div className="file-icon"><FileText/></div><button className="history-main" onClick={()=>openTask(item.id)}><strong>{item.preview||'未命名文本任务'}</strong><span>{item.id} · {new Date(item.created_at).toLocaleString()}</span></button><span className={`risk-level ${item.risk}`}>{item.risk==='high'?'高风险':item.risk==='medium'?'中风险':'低风险'}</span><b>{item.entity_count} 个实体</b><button onClick={()=>openTask(item.id)} title="查看详情"><ChevronRight/></button><button className="icon-danger" onClick={()=>removeTask(item.id)} title="删除任务"><Trash2/></button></div>)}</div>:<div className="queue-empty large"><Clock3/><strong>暂无历史任务</strong><p>在工作台完成一次检测后，记录会自动出现在这里。</p></div>}</section>{selected&&<aside className="panel task-detail"><div className="section-heading"><div><span>TASK SNAPSHOT</span><h2>任务快照</h2></div><button onClick={()=>setSelected(null)}>×</button></div><dl><div><dt>任务编号</dt><dd>{selected.task_id}</dd></div><div><dt>最终版本</dt><dd>v{selected.final_revision}</dd></div><div><dt>人工修订</dt><dd>{selected.has_manual_edits?'是':'否'}</dd></div><div><dt>实体数量</dt><dd>{selected.summary.total}</dd></div></dl><label><span>最终文本</span><textarea readOnly value={selected.final_text}/></label><div className="detail-actions"><button className="btn ghost" onClick={()=>saveJson(`${selected.task_id}.json`,selected)}><Download/>导出快照</button><button className="btn ghost danger" onClick={()=>removeTask(selected.task_id)}><Trash2/>彻底删除</button></div></aside>}</div>}
  {tab==='policy'&&<div className="policy-layout"><section className="panel policy-panel"><div className="section-heading"><div><span>ENTITY POLICIES</span><h2>按实体类型配置默认策略</h2></div><button className="btn primary" onClick={save}>{saved?<Check/>:<Save/>}{saved?'已保存':'保存策略'}</button></div><div className="policy-table"><div className="policy-row policy-head"><span>实体类型</span><span>默认处理策略</span><span>保护级别</span></div>{allEntityTypes.map(key=><div className="policy-row" key={key}><span><i className={`legend-dot entity-${key}`}/><b>{labels[key]}</b><small>{key}</small></span><select value={policies[key]||'mask'} onChange={event=>setPolicies({...policies,[key]:event.target.value as Strategy})}><option value="mask">一致性掩码</option><option value="pseudonymize">语义伪名</option><option value="generalize">层级泛化</option></select><span className={['ID_CARD','PASSPORT','BANK_CARD','PHONE'].includes(key)?'level critical':'level standard'}>{['ID_CARD','PASSPORT','BANK_CARD','PHONE'].includes(key)?'严格':'标准'}</span></div>)}</div></section><aside className="panel model-settings"><div className="section-heading"><div><span>DATA SECURITY</span><h2>生产部署提示</h2></div></div><div className="model-security"><Settings2/><p><strong>原文保留策略</strong><span>答辩环境可保留任务用于复核；生产环境应设置最短保留期，并使用磁盘或数据库加密。</span></p></div><div className="model-security"><ShieldAlert/><p><strong>审计最小暴露</strong><span>全文编辑审计只记录长度、变化字符数和 SHA-256 摘要，不重复保存敏感全文。</span></p></div></aside></div>}
  {tab==='audit'&&<section className="panel history-panel"><div className="table-head"><div><h2>操作审计记录</h2><span>记录人工接受、拒绝、改类、边界、策略、强度和最终稿版本变化。</span></div></div>{data.audits.length?<div className="audit-list">{data.audits.map((item:any)=><div className="audit-row" key={item.id}><Fingerprint/><span><strong>{item.operation}</strong><small>{item.task_id}{item.payload?.span_id?` · span ${item.payload.span_id}`:''}</small></span><time>{new Date(item.created_at).toLocaleString()}</time><code>{item.operation==='edit_text'?`revision ${item.payload?.revision} · changed ${item.payload?.changed_characters}`:`${item.payload?.before||'—'} → ${item.payload?.after||'—'}`}</code></div>)}</div>:<div className="queue-empty large"><Fingerprint/><strong>暂无人工操作</strong><p>复核和编辑操作将按时间顺序记录在此处。</p></div>}</section>}
  </div>
}
