import { useEffect, useState } from 'react'
import { Check, ChevronRight, Clock3, FileText, Fingerprint, Save, Settings2, SlidersHorizontal, Trash2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'
import { allEntityTypes, type EntityType, type Strategy } from '../types'

const labels: Record<EntityType,string> = { PERSON:'姓名',ORG:'机构',LOCATION:'地点',ADDRESS:'详细地址',PHONE:'电话',EMAIL:'邮箱',ID_CARD:'身份证',BANK_CARD:'银行卡',PASSPORT:'护照',CUSTOM:'自定义' }

export default function History(){
  const navigate=useNavigate()
  const [tab,setTab]=useState<'history'|'policy'|'audit'>('history')
  const [data,setData]=useState<any>({items:[],audits:[]})
  const [policies,setPolicies]=useState<Record<string,Strategy>>({})
  const [retention,setRetention]=useState(30)
  const [message,setMessage]=useState('')
  const [saved,setSaved]=useState(false)
  async function refresh(){setData(await api.history())}
  useEffect(()=>{refresh();api.policies().then(x=>setPolicies(x.policies))},[])
  async function save(){await api.savePolicies(policies);setSaved(true);setTimeout(()=>setSaved(false),2000)}
  function openTask(id:string){navigate(`/history/${encodeURIComponent(id)}`)}
  async function removeTask(id:string){if(!window.confirm('确认删除该任务原文、结果和审计记录？'))return;await api.deleteTask(id);await refresh();setMessage('任务已彻底删除。')}
  async function purge(){if(!window.confirm(`确认清除 ${retention} 天以前的全部任务与审计记录？`))return;const result=await api.purgeTasks(retention);await refresh();setMessage(`已清除 ${result.deleted} 个过期任务。`)}
  return <div className="page">{message&&<div className="notice-banner">{message}</div>}<div className="page-tabs"><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><Clock3/>处理历史</button><button className={tab==='policy'?'active':''} onClick={()=>setTab('policy')}><SlidersHorizontal/>默认策略</button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}><Fingerprint/>审计日志</button></div>
  {tab==='history'&&<section className="panel history-panel"><div className="table-head"><div><h2>最近处理任务</h2><span>点击箭头进入完整详情；任务原文可单条删除或按期限清除。</span></div><div className="retention-actions"><label>清除<input type="number" min="1" max="3650" value={retention} onChange={event=>setRetention(Number(event.target.value))}/>天前</label><button className="btn ghost danger" onClick={purge}><Trash2/>执行清除</button></div></div>{data.items.length?<div className="history-list">{data.items.map((item:any)=><div className="history-item" key={item.id}><div className="file-icon"><FileText/></div><button className="history-main" onClick={()=>openTask(item.id)}><strong>{item.preview||'未命名文本任务'}</strong><span>{item.id} · {new Date(item.created_at).toLocaleString()}</span></button><button className="icon-danger" onClick={()=>removeTask(item.id)} title="删除任务"><Trash2 size={13}/></button><span className={`risk-level ${item.risk}`}>{item.risk==='high'?'高风险':item.risk==='medium'?'中风险':'低风险'}</span><b>{item.entity_count} 个实体</b><button onClick={()=>openTask(item.id)} title="查看详情"><ChevronRight/></button></div>)}</div>:<div className="queue-empty large"><Clock3/><strong>暂无历史任务</strong><p>在工作台完成一次检测后，记录会自动出现在这里。</p></div>}</section>}
  {tab==='policy'&&<div className="policy-layout"><section className="panel policy-panel"><div className="section-heading"><div><span>ENTITY POLICIES</span><h2>按实体类型配置默认策略</h2></div><button className="btn primary" onClick={save}>{saved?<Check/>:<Save/>}{saved?'已保存':'保存策略'}</button></div><div className="policy-priority-note"><strong>策略优先级</strong><span>任务选择“按实体类型”时使用本页保存值；选择“统一策略”时，本页配置不参与处理。实体复核中的单独覆盖优先级最高。</span></div><div className="policy-table"><div className="policy-row policy-head"><span>实体类型</span><span>默认处理策略</span><span>保护级别</span></div>{allEntityTypes.map(key=><div className="policy-row" key={key}><span><i className={`legend-dot entity-${key}`}/><b>{labels[key]}</b><small>{key}</small></span><select value={policies[key]||'mask'} onChange={event=>setPolicies({...policies,[key]:event.target.value as Strategy})}><option value="mask">一致性掩码</option><option value="pseudonymize">语义伪名</option><option value="generalize">层级泛化</option></select><span className={['ID_CARD','PASSPORT','BANK_CARD','PHONE'].includes(key)?'level critical':'level standard'}>{['ID_CARD','PASSPORT','BANK_CARD','PHONE'].includes(key)?'严格':'标准'}</span></div>)}</div></section><aside className="panel model-settings"><div className="section-heading"><div><span>MODEL ROUTING</span><h2>模型与路由</h2></div></div><label><span>主核验模型</span><select><option>Qwen3-14B</option><option>Qwen3-14B-AWQ</option><option>Qwen3-8B</option></select></label><label><span>NER 适配器</span><select><option>XLM-RoBERTa NER</option><option>CLUENER 中文模型</option></select></label><div className="route-setting"><div><span>候选复核阈值</span><b>0.78</b></div><input type="range" min="50" max="95" defaultValue="78"/></div><div className="route-setting"><div><span>最大 LLM 路由比例</span><b>30%</b></div><input type="range" min="5" max="100" defaultValue="30"/></div><div className="model-security"><Settings2/><p><strong>隐私安全模式</strong><span>模型服务与应用在同一受控服务器运行，不向第三方发送原文。</span></p></div></aside></div>}
  {tab==='audit'&&<section className="panel history-panel"><div className="table-head"><div><h2>操作审计记录</h2><span>记录人工接受、拒绝、改类、边界、策略、强度和最终稿版本变化。</span></div></div>{data.audits.length?<div className="audit-list">{data.audits.map((item:any)=><div className="audit-row" key={item.id}><Fingerprint/><span><strong>{item.operation}</strong><small>{item.task_id}{item.payload?.span_id?` · span ${item.payload.span_id}`:''}</small></span><time>{new Date(item.created_at).toLocaleString()}</time><code>{item.operation==='edit_text'?`revision ${item.payload?.revision} · changed ${item.payload?.changed_characters}`:`${item.payload?.before||'—'} → ${item.payload?.after||'—'}`}</code></div>)}</div>:<div className="queue-empty large"><Fingerprint/><strong>暂无人工操作</strong><p>复核和编辑操作将按时间顺序记录在此处。</p></div>}</section>}
  </div>
}
